SpbstuMovify/Movify

BackendMock/main.py

1. Init FastAPI App for backend mock
2. Implement fake API services in backend mock
Metadata: OTDELRAZRABOTKI-11

feature(BM): Implement Backend Mock

---

AuthService/.gitignore
AuthService/AuthService.csproj
AuthService/AuthService.sln
AuthService/Controllers/AuthController.cs
AuthService/Program.cs
AuthService/Properties/launchSettings.json
AuthService/appsettings.Development.json
AuthService/appsettings.json

1. Init ASP.NET App for auth service.
2. Add AuthController
Metadata: OTDELRAZRABOTKI-7

[OTDELRAZRABOTKI-7] Init ASP.NET App

---

UI/.dockerignore
UI/Dockerfile
UI/docker_run.ps1

- Added Dockerfile for frontend
- Added powershell script file for easier container running. The command inside gives access to volumes with React app code to the container for HMR support.
- Added dockerignore to prevent containerization of node_modules and other unnecessary files
Metadata: OTDELRAZRABOTKI-57

feature(UI): Added the Dockerfile for React app

---

AuthService/AuthService.csproj
AuthService/Program.cs
AuthService/Properties/launchSettings.json
AuthService/Startup.cs
AuthService/Utils/Encryptor.cs
AuthService/Utils/Extentions.cs
AuthService/Utils/IEncryptor.cs
AuthService/Utils/IJwtBuilder.cs
AuthService/Utils/JwtBuilder.cs
AuthService/Utils/JwtOptions.cs
AuthService/appsettings.Production.json
AuthService/appsettings.json

- Added utils for JWT encryption
- Added Startup class
- Updated the configuration
Metadata: OTDELRAZRABOTKI-23

feature(AS): Added JWT encryption

---

ContentService/build.gradle
ContentService/docker-compose.yml
ContentService/src/main/resources/application.yaml
ContentService/src/main/resources/db/changelog-master.yaml
ContentService/src/main/resources/db/changelog/001-init-movify-service-schema.sql

[OTDELRAZRABOTKI-42] Create database scheme for movify service

---

ContentService/build.gradle
ContentService/config/checkstyle/checkstyle.xml
ContentService/config/checkstyle/suppressions.xml
ContentService/src/main/java/com/polytech/contentservice/common/AgeRestriction.java
ContentService/src/main/java/com/polytech/contentservice/common/Category.java
ContentService/src/main/java/com/polytech/contentservice/common/Genre.java
ContentService/src/main/java/com/polytech/contentservice/common/Quality.java
ContentService/src/main/java/com/polytech/contentservice/config/OpenApiConfiguration.java
ContentService/src/main/java/com/polytech/contentservice/converter/AgeRestrictionConverter.java
ContentService/src/main/java/com/polytech/contentservice/converter/QualityConverter.java
ContentService/src/main/java/com/polytech/contentservice/entity/CastMember.java
ContentService/src/main/java/com/polytech/contentservice/entity/Content.java
ContentService/src/main/java/com/polytech/contentservice/repository/ContentRepository.java
ContentService/src/main/resources/application.yaml

[OTDELRAZRABOTKI-43] Add Content repository

---

ContentService/src/main/java/com/polytech/contentservice/dto/EpisodeDto.java
ContentService/src/main/java/com/polytech/contentservice/entity/Episode.java
ContentService/src/main/java/com/polytech/contentservice/mapper/EpisodeMapper.java
ContentService/src/main/java/com/polytech/contentservice/service/ContentService.java
ContentService/src/main/java/com/polytech/contentservice/service/ContentServiceImpl.java

[OTDELRAZRABOTKI-46] Add Content service

---

ContentService/src/main/java/com/polytech/contentservice/conroller/ContentController.java
ContentService/src/main/java/com/polytech/contentservice/dto/CastMemberDto.java
ContentService/src/main/java/com/polytech/contentservice/dto/ContentDto.java
ContentService/src/main/java/com/polytech/contentservice/mapper/CastMemberMapper.java
ContentService/src/main/java/com/polytech/contentservice/mapper/ContentMapper.java

[OTDELRAZRABOTKI-47] Add Content controller

---

ContentService/src/main/java/com/polytech/contentservice/entity/User.java
ContentService/src/main/java/com/polytech/contentservice/repository/UserRepository.java
ContentService/src/main/resources/db/changelog-master.yaml
ContentService/src/main/resources/db/changelog/002-add-password-field-to-user.sql

[OTDELRAZRABOTKI-51] Add user repository

---

ContentService/src/main/java/com/polytech/contentservice/service/UserService.java
ContentService/src/main/java/com/polytech/contentservice/service/UserServiceImpl.java

[OTDELRAZRABOTKI-52] Add user service

---

ContentService/src/main/java/com/polytech/contentservice/conroller/UserController.java
ContentService/src/main/java/com/polytech/contentservice/dto/UserDto.java
ContentService/src/main/java/com/polytech/contentservice/entity/User.java
ContentService/src/main/java/com/polytech/contentservice/service/UserService.java
ContentService/src/main/java/com/polytech/contentservice/service/UserServiceImpl.java

[OTDELRAZRABOTKI-53] Add user controller

---

ContentService/src/main/java/com/polytech/contentservice/dto/UserDto.java
ContentService/src/main/java/com/polytech/contentservice/entity/User.java
ContentService/src/main/java/com/polytech/contentservice/service/UserServiceImpl.java
ContentService/src/main/resources/db/changelog-master.yaml
ContentService/src/main/resources/db/changelog/003-delete-fields-from-user.sql

[OTDELRAZRABOTKI-61] Fix user table

---

ContentService/src/main/java/com/polytech/contentservice/common/Role.java
ContentService/src/main/java/com/polytech/contentservice/common/UserSearchType.java
ContentService/src/main/java/com/polytech/contentservice/common/converter/AgeRestrictionConverter.java
ContentService/src/main/java/com/polytech/contentservice/common/converter/QualityConverter.java
ContentService/src/main/java/com/polytech/contentservice/common/strategy/SearchUserByEmailStrategy.java
ContentService/src/main/java/com/polytech/contentservice/common/strategy/SearchUserByIdStrategy.java
ContentService/src/main/java/com/polytech/contentservice/common/strategy/SearchUserByLoginStrategy.java
ContentService/src/main/java/com/polytech/contentservice/common/strategy/SearchUserStrategy.java
ContentService/src/main/java/com/polytech/contentservice/config/OpenApiConfiguration.java
ContentService/src/main/java/com/polytech/contentservice/conroller/UserController.java
ContentService/src/main/java/com/polytech/contentservice/dto/UserDto.java
ContentService/src/main/java/com/polytech/contentservice/entity/CastMember.java
ContentService/src/main/java/com/polytech/contentservice/entity/Content.java
ContentService/src/main/java/com/polytech/contentservice/entity/Episode.java
ContentService/src/main/java/com/polytech/contentservice/entity/User.java
ContentService/src/main/java/com/polytech/contentservice/mapper/CastMemberMapper.java
ContentService/src/main/java/com/polytech/contentservice/mapper/ContentMapper.java
ContentService/src/main/java/com/polytech/contentservice/mapper/EpisodeMapper.java
ContentService/src/main/java/com/polytech/contentservice/mapper/UserMapper.java
ContentService/src/main/java/com/polytech/contentservice/repository/ContentRepository.java
ContentService/src/main/java/com/polytech/contentservice/repository/UserRepository.java
ContentService/src/main/java/com/polytech/contentservice/service/AuthService.java
ContentService/src/main/java/com/polytech/contentservice/service/AuthServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/ContentServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/UserSearchService.java
ContentService/src/main/java/com/polytech/contentservice/service/UserSearchServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/UserService.java
ContentService/src/main/java/com/polytech/contentservice/service/UserServiceImpl.java
ContentService/src/main/resources/db/changelog-master.yaml
ContentService/src/main/resources/db/changelog/004-add-role-field-to-user.sql

- Add role colummn to user table
- Add java doc
- Add user search end-point
- Add user mapper
Metadata: OTDELRAZRABOTKI-62

[OTDELRAZRABOTKI-62] Add AuthServiceImpl

---

ContentService/src/main/java/com/polytech/contentservice/dto/LoginUserDto.java
ContentService/src/main/java/com/polytech/contentservice/dto/RegisterUserDto.java
ContentService/src/main/java/com/polytech/contentservice/dto/TokenValidationDto.java
ContentService/src/main/java/com/polytech/contentservice/service/AuthGrpcClientService.java
ContentService/src/main/java/com/polytech/contentservice/service/AuthGrpcClientServiceImpl.java

[OTDELRAZRABOTKI-63] Add AuthGrpcClientServiceImpl

---

UI/docker_run.ps1
UI/src/App.jsx
UI/src/components/Navigation.css
UI/src/components/Navigation.jsx
UI/src/pages/Home.jsx

- Created Navigation to be used in other pages
- Added Navigation component to Home page
- Added Browser Router to App for Links in nav to work and future use
Metadata: OTDELRAZRABOTKI-14

 [OTDELRAZRABOTKI-14] Added Navigation component to React App

---

UI/src/App.jsx
UI/src/components/DropdownMultiSelect.css
UI/src/components/DropdownMultiSelect.jsx
UI/src/pages/Register.css
UI/src/pages/Register.jsx
UI/src/pages/SignInScreen.css
UI/src/pages/SignInScreen.jsx

- Created sign up and sign in page using React hook form
- Created custom dropdown select component which supports multiple selection
- Added new pages to the Browser Router
Metadata: OTDELRAZRABOTKI-17

[OTDELRAZRABOTKI-17] Added sign up and sign in pages to React app

---

UI/src/pages/Register.jsx
UI/src/pages/SignInScreen.jsx
UI/src/services/api.jsx

- Added functions for user and content api requests
- Fixed Register.jsx and SignInScreen.jsx to fit the api
- Fixed a small bug with the repeated password in Register.jsx: when password and repeated password
have matched, and afterwards input in password field was changed, the error didn't appear
Metadata: OTDELRAZRABOTKI-15

[OTDELRAZRABOTKI-15] Added functions for user and content api requests for React app

---

UI/Dockerfile
UI/src/App.jsx
UI/src/contexts/AuthContext.jsx
UI/src/pages/Register.jsx
UI/src/pages/SignInScreen.jsx

- Added AuthContext to React app with useEffect for checking the token on every page enter
- Updated App.jsx, Register.jsx, SignInScreen.jsx and Dockerfile to fit and use AuthContext
- Replaced 400 error code with 404 in SignInScreen.jsx to handle the user not found error properly
Metadata: OTDELRAZRABOTKI-18

[OTDELRAZRABOTKI-18] Added AuthContext to React app

---

UI/src/components/Navigation.css
UI/src/components/Navigation.jsx
UI/src/pages/Home.css
UI/src/pages/Home.jsx

- Both React components are now adaptive
Metadata: OTDELRAZRABOTKI-66

[OTDELRAZRABOTKI-66] Fixed adaptive layout for Home and Navigation for React app

---

AuthService/Dtos/LoginUserRequestDto.cs
AuthService/Dtos/LoginUserResponseDto.cs
AuthService/Dtos/RegisterUserRequestDto.cs
AuthService/Dtos/RegisterUserResponseDto.cs
AuthService/Dtos/ValidateTokenRequestDto.cs
AuthService/Dtos/ValidateTokenResponseDto.cs
AuthService/Grpc/IContentGrpcClient.cs
AuthService/Services/AuthService.cs
AuthService/Services/IAuthService.cs
AuthService/Startup.cs
AuthService/Utils/IJwtBuilder.cs
AuthService/Utils/JwtBuilder.cs
AuthService/Utils/UserClaimsData.cs

- Updated token claims
- Added IAuthService and IContentGrpcClient interfaces
- Impl AuthService class
Metadata: OTDELRAZRABOTKI-24

[OTDELRAZRABOTKI-24] Implement AuthService class

---

ContentService/src/main/java/com/polytech/contentservice/config/GlobalExceptionHandler.java
ContentService/src/main/java/com/polytech/contentservice/conroller/UserController.java
ContentService/src/main/java/com/polytech/contentservice/entity/AuthAttempts.java
ContentService/src/main/java/com/polytech/contentservice/exception/LoginException.java
ContentService/src/main/java/com/polytech/contentservice/repository/AuthAttemptsRepository.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthAttemptsService.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthAttemptsServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthService.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/validation/user/ValidUserLoginParameters.java
ContentService/src/main/java/com/polytech/contentservice/validation/user/ValidUserLoginParametersValidator.java
ContentService/src/main/resources/application.yaml
ContentService/src/main/resources/db/changelog-master.yaml
ContentService/src/main/resources/db/changelog/005-add-auth_attempt_table.sql

[OTDELRAZRABOTKI-67] Add ip validation for login process

---

ContentService/build.gradle
ContentService/src/main/java/com/polytech/contentservice/conroller/ContentController.java
ContentService/src/main/java/com/polytech/contentservice/conroller/UserController.java
ContentService/src/main/java/com/polytech/contentservice/dto/content/ContentDto.java
ContentService/src/main/java/com/polytech/contentservice/dto/content/ContentSearchDto.java
ContentService/src/main/java/com/polytech/contentservice/entity/Content.java
ContentService/src/main/java/com/polytech/contentservice/entity/Episode.java
ContentService/src/main/java/com/polytech/contentservice/entity/PersonalList.java
ContentService/src/main/java/com/polytech/contentservice/entity/User.java
ContentService/src/main/java/com/polytech/contentservice/mapper/CastMemberMapper.java
ContentService/src/main/java/com/polytech/contentservice/mapper/ContentMapper.java
ContentService/src/main/java/com/polytech/contentservice/repository/CastMemberRepository.java
ContentService/src/main/java/com/polytech/contentservice/repository/ContentRepository.java
ContentService/src/main/java/com/polytech/contentservice/repository/PersonalListRepository.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthAttemptsServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/content/ContentService.java
ContentService/src/main/java/com/polytech/contentservice/service/content/ContentServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/user/UserService.java
ContentService/src/main/java/com/polytech/contentservice/service/user/UserServiceImpl.java
ContentService/src/main/resources/db/changelog-master.yaml
ContentService/src/main/resources/db/changelog/001-init-movify-service-schema.sql
ContentService/src/main/resources/db/changelog/007-add-year-field-to-content.sql

[OTDELRAZRABOTKI-69] Add PersonalListRepository implementation

---

ContentService/src/main/java/com/polytech/contentservice/dto/personallist/PersonalListDto.java
ContentService/src/main/java/com/polytech/contentservice/service/personallist/PersonalListService.java
ContentService/src/main/java/com/polytech/contentservice/service/personallist/PersonalListServiceImpl.java

[OTDELRAZRABOTKI-70] Add PersonalListServiceImpl implementation

---

MediaService/.gitignore
MediaService/Controllers/BucketController.cs
MediaService/MediaService.csproj
MediaService/MediaService.http
MediaService/MediaService.sln
MediaService/Program.cs
MediaService/Properties/launchSettings.json
MediaService/Startup.cs
MediaService/appsettings.Development.json
MediaService/appsettings.Production.json
MediaService/appsettings.json

- Init ASP.NET App for media service
- Add BucketController
Metadata: OTDELRAZRABOTKI-29

[OTDELRAZRABOTKI-29] Init ASP.NET App

---

MediaService/Controllers/BucketController.cs
MediaService/MediaService.csproj
MediaService/Models/DownloadedFile.cs
MediaService/Repositories/BucketRepository.cs
MediaService/Repositories/IBucketRepository.cs
MediaService/Startup.cs

- Add AWSSDK packages to project
- Add IBucketRepository
- Implement BucketRepository
Metadata: OTDELRAZRABOTKI-34

feature(MS): Implement BucketRepository

---

MediaService/Dtos/Bucket/BucketDto.cs
MediaService/Dtos/Bucket/CreateBucketDto.cs
MediaService/Dtos/Bucket/DeleteBucketDto.cs
MediaService/Dtos/FileInfo/CreateFileInfoDto.cs
MediaService/Dtos/FileInfo/DeleteFileInfoDto.cs
MediaService/Dtos/FileInfo/FileInfoDto.cs
MediaService/Dtos/FileInfo/GetFileInfoDto.cs
MediaService/Dtos/FileInfo/GetFilesInfoDto.cs
MediaService/Dtos/FileInfo/UpdateFileInfoDto.cs
MediaService/Dtos/S3/S3BucketDto.cs
MediaService/Dtos/S3/S3ObjectDto.cs
MediaService/Exceptions/InternalServerException.cs
MediaService/Exceptions/ResourceNotFoundException.cs
MediaService/Repositories/DownloadedFile.cs
MediaService/Services/BucketService.cs
MediaService/Services/FileProcessingService.cs
MediaService/Services/IBucketService.cs
MediaService/Utils/FileProcessingQueue.cs
MediaService/Utils/FileProcessingTask.cs
MediaService/Utils/IFileProcessingQueue.cs

- Implement FileProcessingService
- Add IBucketRepository
- Implement BucketRepository
Metadata: OTDELRAZRABOTKI-30

[OTDELRAZRABOTKI-30] Implement BucketService

---

MediaService/Controllers/BucketController.cs
MediaService/Models/DownloadedFile.cs
MediaService/Repositories/BucketRepository.cs
MediaService/Repositories/IBucketRepository.cs
MediaService/Services/BucketService.cs
MediaService/Services/FileProcessingService.cs
MediaService/Services/IBucketService.cs
MediaService/Startup.cs
MediaService/Utils/Exceptions/InternalServerException.cs
MediaService/Utils/Exceptions/ResourceNotFoundException.cs
MediaService/Utils/FileProcessing/FileProcessingQueue.cs
MediaService/Utils/FileProcessing/FileProcessingTask.cs
MediaService/Utils/FileProcessing/IFileProcessingQueue.cs
MediaService/Utils/Middleware/ExceptionHandlingMiddleware.cs

- Implement ExceptionHandlingMiddleware
- Implement BucketController
- Refactor code
Metadata: OTDELRAZRABOTKI-31

[OTDELRAZRABOTKI-31] Implement BucketController

---

AuthService/Dockerfile
ContentService/Dockerfile
ContentService/src/main/resources/application.yaml
docker-compose.yml

[OTDELRAZRABOTKI-56] Add docker compose file for all project

---

AuthService/appsettings.Production.json

[OTDELRAZRABOTKI-56] Fix c# configuration

---

MediaService/Controllers/BucketController.cs
MediaService/Dtos/Claims/ClaimsDto.cs
MediaService/Grpc/AuthGrpcClient.cs
MediaService/Grpc/IAuthGrpcClient.cs
MediaService/MediaService.csproj
MediaService/Protos/auth.proto
MediaService/Startup.cs
MediaService/Utils/Extentions.cs
MediaService/Utils/JwtOptions.cs
MediaService/Utils/Middleware/JwtMiddleware.cs
MediaService/appsettings.Development.json
MediaService/appsettings.Production.json
MediaService/appsettings.json

- Implement JwtMiddleware
- Update BucketController
Metadata: OTDELRAZRABOTKI-32

[OTDELRAZRABOTKI-32] Added JWT authorization

---

ContentService/src/main/java/com/polytech/contentservice/config/GlobalExceptionHandler.java
ContentService/src/main/java/com/polytech/contentservice/entity/Episode.java
ContentService/src/main/java/com/polytech/contentservice/repository/EpisodeRepository.java
ContentService/src/main/resources/db/changelog-master.yaml
ContentService/src/main/resources/db/changelog/008-alter-episode-table.sql

[OTDELRAZRABOTKI-48] Add EpisodeRepository

---

ContentService/src/main/java/com/polytech/contentservice/conroller/UserController.java
ContentService/src/main/java/com/polytech/contentservice/dto/personallist/PersonalListDto.java
ContentService/src/main/java/com/polytech/contentservice/mapper/EpisodeMapper.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthService.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/episode/EpisodeService.java
ContentService/src/main/java/com/polytech/contentservice/service/episode/EpisodeServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/user/UserService.java
ContentService/src/main/java/com/polytech/contentservice/service/user/UserServiceImpl.java

- Add recovery password for users
- Add crud for episodes
Metadata: OTDELRAZRABOTKI-49

[OTDELRAZRABOTKI-49] Add EpisodeService

---

ContentService/src/main/java/com/polytech/contentservice/conroller/EpisodeController.java
ContentService/src/main/java/com/polytech/contentservice/dto/episode/EpisodeDto.java

[OTDELRAZRABOTKI-50] Add EpisodeController

---

ContentService/src/main/java/com/polytech/contentservice/grpc/ContentGrpcController.java
ContentService/src/main/proto/content.proto

[OTDELRAZRABOTKI-72] Update ContentGrpcController

---

README.md

[OTDELRAZRABOTKI-56] Update README.md

---

MediaService/Controllers/BucketController.cs
MediaService/Dtos/Content/ContentImageUrlDto.cs
MediaService/Dtos/Content/EpisodeVideoUrlDto.cs
MediaService/Dtos/FileInfo/CreateFileInfoDto.cs
MediaService/Dtos/FileInfo/UpdateFileInfoDto.cs
MediaService/Grpc/AuthGrpcClient.cs
MediaService/Grpc/ContentGrpcClient.cs
MediaService/Grpc/IContentGrpcClient.cs
MediaService/MediaService.csproj
MediaService/Protos/auth.proto
MediaService/Protos/content.proto
MediaService/Services/BucketService.cs
MediaService/Services/FileProcessingService.cs
MediaService/Startup.cs
MediaService/Utils/Extentions.cs
MediaService/Utils/FileProcessing/FileDestination.cs
MediaService/Utils/FileProcessing/FileProcessingTask.cs
MediaService/Utils/FileProcessing/FileStatus.cs
MediaService/appsettings.Production.json

- Implement ContentGrpcClient
- Update FileProcessingService
Metadata: OTDELRAZRABOTKI-73

[OTDELRAZRABOTKI-73] Implement ContentGrpcClient

---

AuthService/Protos/auth.proto
ContentService/src/main/proto/auth.proto

[OTDELRAZRABOTKI-74] Fix auth.proto

---

AuthService/AuthService.csproj
AuthService/Controllers/AuthController.cs
AuthService/Dtos/LoginUserRequestDto.cs
AuthService/Dtos/LoginUserResponseDto.cs
AuthService/Dtos/RegisterUserRequestDto.cs
AuthService/Dtos/RegisterUserResponseDto.cs
AuthService/Dtos/ValidateTokenRequestDto.cs
AuthService/Dtos/ValidateTokenResponseDto.cs
AuthService/Grpc/AuthGrpcServer.cs
AuthService/Grpc/ContentGrpcClient.cs
AuthService/Grpc/IContentGrpcClient.cs
AuthService/Program.cs
AuthService/Properties/launchSettings.json
AuthService/Protos/content.proto
AuthService/Services/AuthService.cs
AuthService/Services/IAuthService.cs
AuthService/Startup.cs
AuthService/Utils/Encryptor.cs
AuthService/Utils/Extentions.cs
AuthService/Utils/IEncryptor.cs
AuthService/Utils/IJwtBuilder.cs
AuthService/Utils/JwtBuilder.cs
AuthService/Utils/JwtOptions.cs
AuthService/Utils/UserClaimsData.cs
AuthService/appsettings.Production.json

- Fix content.proto
- Update config
Metadata: OTDELRAZRABOTKI-75

[OTDELRAZRABOTKI-75] Fix content.proto

---

MediaService/.gitignore
MediaService/Controllers/BucketController.cs
MediaService/Grpc/AuthGrpcClient.cs
MediaService/Grpc/ContentGrpcClient.cs
MediaService/Properties/launchSettings.json
MediaService/Repositories/BucketRepository.cs
MediaService/Repositories/DownloadedFile.cs
MediaService/Repositories/IBucketRepository.cs
MediaService/Services/BucketService.cs
MediaService/Services/IBucketService.cs
MediaService/Startup.cs
MediaService/Utils/FileProcessing/FileProcessingTask.cs
MediaService/appsettings.Development.json
MediaService/appsettings.Production.json
MediaService/appsettings.json
docker-compose.yml

- Fix file processing
- Add Dockerfile
- Update config
Metadata: OTDELRAZRABOTKI-33

[OTDELRAZRABOTKI-33] Add Dockerfile

---

MediaService/Dockerfile
MediaService/Repositories/UploadedFile.cs

- Fix Dockerfile
Metadata: OTDELRAZRABOTKI-76

[OTDELRAZRABOTKI-76] Fix Dockerfile for media service

---

Gateway/Dockerfile
Gateway/nginx.conf
docker-compose.yml

[OTDELRAZRABOTKI-10] Add nginx api gateway config

---

MediaService/Controllers/BucketController.cs
MediaService/Services/FileProcessingService.cs
MediaService/Startup.cs
MediaService/Utils/Extentions.cs
MediaService/Utils/Middleware/JwtMiddleware.cs

[OTDELRAZRABOTKI-77] Fix JWT token handling

---

ChunkerService/.gitignore
ChunkerService/ChunkerService.csproj
ChunkerService/ChunkerService.sln
ChunkerService/Program.cs
ChunkerService/Properties/launchSettings.json
ChunkerService/Protos/chunker.proto
ChunkerService/Protos/media.proto
ChunkerService/Services/GreeterService.cs
ChunkerService/Startup.cs
ChunkerService/appsettings.Development.json
ChunkerService/appsettings.Production.json
ChunkerService/appsettings.json

[OTDELRAZRABOTKI-35] Init ASP.NET App

---

ChunkerService/Dtos/S3/S3ObjectDto.cs
ChunkerService/Program.cs
ChunkerService/Repositories/ChunkerRepository.cs
ChunkerService/Repositories/DownloadedFile.cs
ChunkerService/Repositories/IChunkerRepository.cs
ChunkerService/Repositories/UploadedFile.cs
ChunkerService/Startup.cs
ChunkerService/Utils/Exceptions/InternalServerException.cs
ChunkerService/Utils/Exceptions/ResourceNotFoundException.cs

[OTDELRAZRABOTKI-37] Add ChunkerRepository

---

ChunkerService/Grpc/ChunkerGrpcServer.cs
ChunkerService/Startup.cs
ChunkerService/appsettings.Development.json
ChunkerService/appsettings.json

[OTDELRAZRABOTKI-39] Add ChunkerGrpcServer

---

UI/src/App.jsx
UI/src/components/ProtectedRoute.jsx
UI/src/contexts/AuthContext.jsx
UI/src/pages/Films.jsx
UI/src/pages/Home.jsx
UI/src/pages/Profile.css
UI/src/pages/Profile.jsx
UI/src/pages/Register.css
UI/src/pages/Register.jsx
UI/src/pages/SignInScreen.css
UI/src/services/api.jsx

- Added the profile page with all its functionality
- Added new api requests to api.jsx
- Added protected route component for routes that require login
- Added routing to the profile page using protected route
- Minor fixes to css of other pages
Metadata: OTDELRAZRABOTKI-19

[OTDELRAZRABOTKI-19] Added profile page to React app

---

ContentService/src/main/java/com/polytech/contentservice/config/GlobalExceptionHandler.java
ContentService/src/main/java/com/polytech/contentservice/conroller/UserController.java
ContentService/src/main/java/com/polytech/contentservice/dto/personallist/PersonalListDeletionDto.java
ContentService/src/main/java/com/polytech/contentservice/exception/UnauthorisedException.java
ContentService/src/main/java/com/polytech/contentservice/repository/PersonalListRepository.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthService.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/personallist/PersonalListService.java
ContentService/src/main/java/com/polytech/contentservice/service/personallist/PersonalListServiceImpl.java

[OTDELRAZRABOTKI-70] Fix personal list remove method

---

UI/src/App.jsx
UI/src/pages/FavoriteFilms.jsx
UI/src/pages/Films.jsx
UI/src/services/api.jsx

- Added the page with films and series marked as favorites
- Updated api.jsx accordingly
- Fixed favorite functionality on Films page
- Added routing to the favorites page using protected route
Metadata: OTDELRAZRABOTKI-20

[OTDELRAZRABOTKI-20] Added Favorite Films page to React app

---

ChunkerService/Hls/HlsCreator.cs
ChunkerService/Hls/HlsVariant.cs
ChunkerService/Hls/IHlsCreator.cs
ChunkerService/Startup.cs

[OTDELRAZRABOTKI-36] Add HlsCreator

---

ContentService/src/main/java/com/polytech/contentservice/conroller/ContentController.java
ContentService/src/main/java/com/polytech/contentservice/conroller/EpisodeController.java
ContentService/src/main/java/com/polytech/contentservice/conroller/UserController.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthGrpcClientImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthService.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthServiceImpl.java

- Add role validation
Metadata: OTDELRAZRABOTKI-68

OTDELRAZRABOTKI-68 Fix token validation

---

UI/src/contexts/AuthContext.jsx
UI/src/pages/FavoriteFilms.jsx
UI/src/pages/Films.css
UI/src/pages/Films.jsx
UI/src/pages/Profile.jsx
UI/src/services/api.jsx

[OTDELRAZRABOTKI-78] Fix React app issues

---

ContentService/Dockerfile

[OTDELRAZRABOTKI-80] Update Dockerfile

---

ChunkerService/.dockerignore
ChunkerService/ChunkerService.csproj
ChunkerService/Dockerfile
docker-compose.yml

- Add Dockerfile for Chunker Service
- Update docker-compose.yml
Metadata: OTDELRAZRABOTKI-40

[OTDELRAZRABOTKI-40] Add Dockerfile for Chuncker Service

---

ChunkerService/.gitignore
ChunkerService/Grpc/ChunkerGrpcServer.cs
ChunkerService/Hls/HlsCreator.cs
ChunkerService/Hls/IHlsCreator.cs
ChunkerService/Program.cs
ChunkerService/Protos/chunker.proto
ChunkerService/Services/FileProcessingService.cs

- Update chunker.proto
- Add cancellation token support to HlsCreator
- Update FileProcessingService
Metadata: OTDELRAZRABOTKI-81

[OTDELRAZRABOTKI-81] Add external interrupt to ffmpeg script

---

MediaService/.gitignore
MediaService/Controllers/BucketController.cs
MediaService/Dtos/FileInfo/UploadedFileInfoDto.cs
MediaService/Program.cs
MediaService/Services/BucketService.cs
MediaService/Services/FileProcessingService.cs
MediaService/Services/IBucketService.cs
MediaService/Startup.cs
MediaService/Utils/FileProcessing/FileProcessingTask.cs

[OTDELRAZRABOTKI-82] Add support for uploading large files

---

ChunkerService/Dockerfile
ChunkerService/Properties/launchSettings.json
ChunkerService/Startup.cs
ChunkerService/appsettings.Production.json
Gateway/nginx.conf
MediaService/Dockerfile
MediaService/Dtos/Chunker/ProcessVideoDto.cs
MediaService/Dtos/Chunker/ProcessVideoDtoCallbackFailedDto.cs
MediaService/Dtos/Chunker/ProcessVideoDtoCallbackSuccessDto.cs
MediaService/Grpc/ChunkerGrpcClient.cs
MediaService/Grpc/IChunkerGrpcClient.cs
MediaService/Grpc/MediaGrpcServer.cs
MediaService/MediaService.csproj
MediaService/Protos/chunker.proto
MediaService/Protos/media.proto
MediaService/Services/ChunkerCallbackService.cs
MediaService/Services/FileProcessingService.cs
MediaService/Services/IChunkerCallbackService.cs
MediaService/Startup.cs
MediaService/appsettings.Development.json
MediaService/appsettings.Production.json
MediaService/appsettings.json
docker-compose.yml

[OTDELRAZRABOTKI-83] Add Chuncker Service support for Media Service

---

UI/src/pages/Films.jsx

[OTDELRAZRABOTKI-85] Fixed add/remove from favorites on Film page

---

ContentService/src/main/java/com/polytech/contentservice/mapper/ContentMapper.java

[OTDELRAZRABOTKI-41] Fix update of content with cast members

---

Gateway/nginx.conf
UI/src/pages/FilmDetail.jsx
UI/src/services/api.jsx

[OTDELRAZRABOTKI-84] Add form for episodes

---

ContentService/src/main/java/com/polytech/contentservice/entity/Episode.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthGrpcClientImpl.java

[OTDELRAZRABOTKI-41] Fix cascade delete for episode entity

---

ContentService/src/main/java/com/polytech/contentservice/conroller/ContentController.java
ContentService/src/main/java/com/polytech/contentservice/entity/Content.java
ContentService/src/main/java/com/polytech/contentservice/service/content/ContentService.java
ContentService/src/main/java/com/polytech/contentservice/service/content/ContentServiceImpl.java

[OTDELRAZRABOTKI-41] Add delete for Content

---

ContentService/src/main/java/com/polytech/contentservice/mapper/CastMemberMapper.java

[OTDELRAZRABOTKI-41] Fix content update

---

UI/src/App.jsx
UI/src/components/Navigation.jsx
UI/src/pages/Rights.jsx
UI/src/services/api.jsx

[OTDELRAZRABOTKI-22] Add a form for granting administrator rights

---

ContentService/src/main/java/com/polytech/contentservice/mapper/CastMemberMapper.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthAttemptsService.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthAttemptsServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthGrpcClientImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthService.java
ContentService/src/main/resources/application.yaml

[OTDELRAZRABOTKI-55] Fix login max attempts

---

ContentService/src/main/java/com/polytech/contentservice/repository/AuthAttemptsRepository.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthAttemptsService.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthAttemptsServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthGrpcClientImpl.java

[OTDELRAZRABOTKI-55] Fix cast members deletion when uploading picture for content

---

ContentService/src/main/java/com/polytech/contentservice/mapper/CastMemberMapper.java

[OTDELRAZRABOTKI-41] Fix creating cast members

---

docker-compose.yml

[OTDELRAZRABOTKI-12] Added UI to docker-compose

---

.github/workflows/auto-rebase.yml

[OTDELRAZRABOTKI-120] Add auto-rebase Github Action

---

AuthService/src/AuthService/Utils/Configuration/Extentions.cs
AuthService/src/AuthService/Utils/Configuration/GrpcClientOptions.cs
AuthService/tests/AuthService.Tests/Utils/Configuration/GrpcClientOptionsTest.cs

- Add DataAnnotations to GrpcClientOptions
- Refactor Extentions
- Add Unit Tests on DataAnnotations for GrpcClientOptions
Metadata: OTDELRAZRABOTKI-96

[OTDELRAZRABOTKI-96] Add Unit Tests for GrpcClientOptions

---

AuthService/src/AuthService/Utils/Encryption/Encryptor.cs
AuthService/src/AuthService/Utils/Encryption/IEncryptor.cs
AuthService/tests/AuthService.Tests/Utils/Encryption/EncryptorTest.cs

- Refactor IEncryptor and Encryptor
- Add Unit Tests for Encryptor
Metadata: OTDELRAZRABOTKI-97

[OTDELRAZRABOTKI-97] Add Unit Tests for Encryptor

---

AuthService/src/AuthService/Utils/Jwt/UserClaimsData.cs
AuthService/tests/AuthService.Tests/Utils/Jwt/JwtBuilderTest.cs

- Refactor UserClaimsData
- Add Unit Tests for JwtBuilder
Metadata: OTDELRAZRABOTKI-98

[OTDELRAZRABOTKI-98] Add Unit Tests for JwtBuilder

---

AuthService/src/AuthService/Grpc/ContentGrpcClient.cs
AuthService/src/AuthService/Grpc/IContentGrpcClient.cs
AuthService/tests/AuthService.Tests/Grpc/ContentGrpcClientTest.cs

- Refactor IContentGrpcClient and ContentGrpcClient
- Add Unit Tests for ContentGrpcClient
Metadata: OTDELRAZRABOTKI-99

[OTDELRAZRABOTKI-99] Add Unit Tests for ContentGrpcClient

---

AuthService/src/AuthService/Dtos/LoginUserRequestDto.cs
AuthService/src/AuthService/Dtos/LoginUserResponseDto.cs
AuthService/src/AuthService/Dtos/RegisterUserRequestDto.cs
AuthService/src/AuthService/Dtos/RegisterUserResponseDto.cs
AuthService/src/AuthService/Dtos/ValidateTokenRequestDto.cs
AuthService/src/AuthService/Dtos/ValidateTokenResponseDto.cs
AuthService/src/AuthService/Services/AuthService.cs
AuthService/src/AuthService/Utils/Exceptions/AuthServiceException.cs
AuthService/src/AuthService/Utils/Exceptions/InvalidCredentialsException.cs
AuthService/src/AuthService/Utils/Exceptions/TokenValidationException.cs
AuthService/tests/AuthService.Tests/Services/AuthServiceTest.cs

- Refactor Dtos and AuthService
- Add custom exceptions
- Add Unit Tests for AuthService
Metadata: OTDELRAZRABOTKI-100

[OTDELRAZRABOTKI-100] Add Unit Tests for AuthService

---

AuthService/src/AuthService/Grpc/AuthGrpcServer.cs
AuthService/tests/AuthService.Tests/Grpc/AuthGrpcServerTest.cs

- Refactor AuthGrpcServer
- Add Unit Tests for AuthGrpcServer
Metadata: OTDELRAZRABOTKI-100

[OTDELRAZRABOTKI-100] Add Unit Tests for AuthGrpcServer

---

AuthService/src/AuthService/Grpc/Interceptors/ErrorHandlerInterceptor.cs
AuthService/tests/AuthService.Tests/Grpc/Interceptors/ErrorHandlerInterceptorTest.cs
AuthService/tests/AuthService.Tests/Grpc/Interceptors/TestServerCallContext.cs

- Add ErrorHandlerInterceptor
- Add Unit Tests for ErrorHandlerInterceptor
Metadata: OTDELRAZRABOTKI-102

[OTDELRAZRABOTKI-102] Add Unit Tests for ErrorHandlerInterceptor

---

AuthService/src/AuthService/Grpc/Interceptors/ValidationInterceptor.cs
AuthService/src/AuthService/Program.cs
AuthService/tests/AuthService.Tests/Grpc/Interceptors/ValidationInterceptorTest.cs

- Add ValidationInterceptor
- Update Program
- Add Unit Tests for ValidationInterceptor
Metadata: OTDELRAZRABOTKI-103

[OTDELRAZRABOTKI-103] Add Unit Tests for ValidationInterceptor

---

UI/.gitignore
UI/src/App.jsx
UI/src/components/general/ProtectedRoute.jsx

[OTDELRAZRABOTKI-135] Fix routing to grant admin rights page

---

ContentService/build.gradle
ContentService/src/test/java/com/polytech/contentservice/conroller/UserControllerTest.java

[OTDELRAZRABOTKI-138] Add unit tests for user controller

---

ContentService/src/test/java/com/polytech/contentservice/conroller/EpisodeControllerTest.java

[OTDELRAZRABOTKI-139] Add unit tests for episode controller

---

ContentService/src/main/java/com/polytech/contentservice/dto/content/ContentSearchDto.java
ContentService/src/test/java/com/polytech/contentservice/conroller/ContentControllerTest.java

[OTDELRAZRABOTKI-140] Add unit tests for content controller

---

ContentService/src/test/java/com/polytech/contentservice/validation/user/ValidUserSearchParametersValidatorTest.java

[OTDELRAZRABOTKI-142] Add unit tests for ValidUserSearchParametersValidator

---

ContentService/build.gradle
ContentService/src/test/java/com/polytech/contentservice/common/converter/QualityConverterTest.java

[OTDELRAZRABOTKI-144] Add unit tests for QualityConverter

---

ContentService/src/test/java/com/polytech/contentservice/common/converter/AgeRestrictionConverterTest.java

[OTDELRAZRABOTKI-143] Add unit tests for AgeRestrictionConverter

---

UI/craco.config.cjs
UI/package.json
UI/src/App.jsx
UI/src/App.test.jsx
UI/src/__mocks__/contexts/AuthContext.jsx
UI/src/__mocks__/services/api.jsx
UI/src/components/general/ProtectedRoute.test.jsx
UI/src/configs/routesConfig.jsx
UI/src/pages/FilmDetail.jsx
UI/src/pages/Profile.jsx
UI/vite.config.js

[OTDELRAZRABOTKI-111] Add unit tests for the routing system

---

UI/src/components/general/Navigation.jsx
UI/src/components/general/Navigation.test.jsx
UI/src/configs/testConfig.jsx
UI/src/pages/FavoriteFilms.jsx

[OTDELRAZRABOTKI-109] Add unit tests for Navigation components

---

UI/src/components/general/Navigation.test.jsx
UI/src/configs/testConfig.jsx
UI/src/contexts/AuthContext.jsx
UI/src/contexts/AuthContext.test.jsx

[OTDELRAZRABOTKI-112] Add unit tests for AuthContext

---

UI/src/components/general/DropdownMultiSelect.jsx
UI/src/components/general/DropdownMultiSelect.test.jsx

[OTDELRAZRABOTKI-107] Add unit tests for DropdownMultiSelect component

---

UI/src/components/general/DropdownMultiSelect.test.jsx
UI/src/components/general/EditableField.jsx
UI/src/components/general/EditableField.test.jsx

[OTDELRAZRABOTKI-108] Add unit tests for EditableField component

---

UI/package-lock.json
UI/package.json
UI/src/components/general/UpdatableImage.jsx
UI/src/components/general/UpdatableImage.test.jsx

[OTDELRAZRABOTKI-110] Add unit tests for UpdatableImage component

---

ContentService/build.gradle
ContentService/src/main/java/com/polytech/contentservice/grpc/ContentGrpcController.java
ContentService/src/main/java/com/polytech/contentservice/mapper/UserMapper.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthGrpcClient.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthGrpcClientImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/auth/AuthServiceImpl.java
ContentService/src/main/java/com/polytech/contentservice/service/user/UserServiceImpl.java
ContentService/src/main/proto/auth.proto
ContentService/src/main/proto/content.proto
ContentService/src/test/java/com/polytech/contentservice/mapper/UserMapperTest.java

[OTDELRAZRABOTKI-148] Add unit tests for UserMapper

---

ContentService/src/test/java/com/polytech/contentservice/mapper/CastMemberMapperTest.java
ContentService/src/test/java/com/polytech/contentservice/validation/user/ValidUserLoginParametersValidatorTest.java
ContentService/src/test/java/com/polytech/contentservice/validation/user/ValidUserSearchParametersValidatorTest.java

[OTDELRAZRABOTKI-145] Add unit tests for CastMemberMapper

---

ContentService/src/test/java/com/polytech/contentservice/mapper/ContentMapperTest.java

[OTDELRAZRABOTKI-146] Add unit tests for ContentMapper

---

ContentService/src/test/java/com/polytech/contentservice/mapper/EpisodeMapperTest.java

[OTDELRAZRABOTKI-147] Add unit tests for EpisodeMapper

---

ContentService/src/test/java/com/polytech/contentservice/service/auth/AuthServiceImplTest.java

[OTDELRAZRABOTKI-150] Add unit tests for AuthServiceImpl

---

ContentService/src/test/java/com/polytech/contentservice/service/content/ContentServiceImplTest.java

[OTDELRAZRABOTKI-151] Add unit tests for ContentServiceImpl

---

ContentService/src/test/java/com/polytech/contentservice/service/episode/EpisodeServiceImplTest.java

[EpisodeServiceImpl] Add unit tests for EpisodeServiceImpl

---

ContentService/src/test/java/com/polytech/contentservice/service/personallist/PersonalListServiceImplTest.java

[OTDELRAZRABOTKI-153] Add unit tests for PersonalListServiceImpl

---

ContentService/src/test/java/com/polytech/contentservice/service/user/UserServiceImplTest.java

[OTDELRAZRABOTKI-154] Add unit tests for UserServiceImpl

---

UI/src/pages/Home.test.jsx

[OTDELRAZRABOTKI-105] Add unit tests for Home component

---

UI/src/__mocks__/contexts/AuthContext.jsx
UI/src/components/general/UpdatableImage.test.jsx
UI/src/contexts/AuthContext.test.jsx
UI/src/pages/SignInScreen.test.jsx

[OTDELRAZRABOTKI-118] Add unit tests for SignInScreen component

---

UI/src/pages/Register.test.jsx

[OTDELRAZRABOTKI-117] Add unit tests for Register component

---

UI/src/pages/Rights.test.jsx

[OTDELRAZRABOTKI-119] Add unit tests for Rights component

---

UI/src/components/profile_components/ConfirmationModal.test.jsx

[OTDELRAZRABOTKI-131] Add unit tests for ConfirmationModal component

---

MediaService/tests/MediaService.Tests/Utils/Handlers/ErrorResponseHandlerTest.cs
MediaService/tests/MediaService.Tests/Utils/Handlers/ExternalAuthenticationHandlerTest.cs

[OTDELRAZRABOTKI-156] Add Unit Tests for Handlers

---

MediaService/tests/MediaService.Tests/Utils/Middleware/AuthorizationHandlingMiddlewareTest.cs
MediaService/tests/MediaService.Tests/Utils/Middleware/ExceptionHandlingMiddlewareTest.cs

[OTDELRAZRABOTKI-157] Add Unit Tests for Middleware

---

MediaService/tests/MediaService.Tests/Grpc/Clients/AuthGrpcClientTest.cs
MediaService/tests/MediaService.Tests/Grpc/Clients/ChunkerGrpcClientTest.cs
MediaService/tests/MediaService.Tests/Grpc/Clients/ContentGrpcClientTest.cs

[OTDELRAZRABOTKI-158] Add Unit Tests for Grpc.Clients

---

MediaService/tests/MediaService.Tests/Services/BucketServiceTest.cs

[OTDELRAZRABOTKI-159] Add Unit Tests for BucketService

---

MediaService/tests/MediaService.Tests/Repositories/BucketRepositoryTest.cs

[OTDELRAZRABOTKI-160] Add Unit Tests for BucketRepository

---

MediaService/tests/MediaService.Tests/FileProcessing/FileProcessors/ContentImageFileProcessorTest.cs
MediaService/tests/MediaService.Tests/FileProcessing/FileProcessors/EpisodeVideoFileProcessorTest.cs
MediaService/tests/MediaService.Tests/FileProcessing/FileProcessors/FileProcessorFactoryTest.cs
MediaService/tests/MediaService.Tests/FileProcessing/FileProcessors/InternalFileProcessorTest.cs

[OTDELRAZRABOTKI-162] Add Unit Tests for FileProcessors

---

MediaService/tests/MediaService.Tests/Services/FileProcessingServiceTest.cs

[OTDELRAZRABOTKI-168] Add Unit Tests for FileProcessingService

---

MediaService/tests/MediaService.Tests/Grpc/Interceptors/ErrorHandlerInterceptorTest.cs
MediaService/tests/MediaService.Tests/Grpc/Interceptors/TestServerCallContext.cs
MediaService/tests/MediaService.Tests/Grpc/Interceptors/ValidationInterceptorTest.cs

[OTDELRAZRABOTKI-163] Add Unit Tests for Grpc.Interceptors

---

MediaService/tests/MediaService.Tests/Controllers/Validators/CreateBucketRequestValidatorTest.cs
MediaService/tests/MediaService.Tests/Controllers/Validators/CreateFileRequestValidatorTest.cs
MediaService/tests/MediaService.Tests/Controllers/Validators/DeleteBucketRequestValidatorTest.cs
MediaService/tests/MediaService.Tests/Controllers/Validators/DeleteFileRequestValidatorTest.cs
MediaService/tests/MediaService.Tests/Controllers/Validators/GetFileRequestValidatorTest.cs
MediaService/tests/MediaService.Tests/Controllers/Validators/GetFilesRequestValidatorTest.cs
MediaService/tests/MediaService.Tests/Controllers/Validators/UpdateFileRequestValidatorTest.cs
MediaService/tests/MediaService.Tests/Controllers/Validators/ValidatorExtensionsTest.cs

[OTDELRAZRABOTKI-165] Add Unit Tests for Controllers.Validators

---

MediaService/tests/MediaService.Tests/Controllers/BucketControllerTest.cs

[OTDELRAZRABOTKI-166] Add Unit Tests for BucketController

---

MediaService/tests/MediaService.Tests/Grpc/MediaGrpcServerTest.cs

[OTDELRAZRABOTKI-167] Add Unit Tests for MediaGrpcServer

---

UI/src/App.test.jsx
UI/src/components/general/Navigation.test.jsx
UI/src/components/general/ProtectedRoute.test.jsx
UI/src/components/profile_components/ChangePassword.test.jsx
UI/src/contexts/AuthContext.test.jsx
UI/src/pages/Home.test.jsx
UI/src/pages/Register.test.jsx
UI/src/pages/Rights.test.jsx
UI/src/pages/SignInScreen.test.jsx

[OTDELRAZRABOTKI-130] Add unit tests for ChangePasswordForm component

---

MediaService/src/MediaService/Services/FileProcessingService.cs
MediaService/tests/MediaService.Tests/Services/FileProcessingServiceTest.cs

[OTDELRAZRABOTKI-90] Fix filling of FileData record fields

---

UI/Dockerfile
UI/package-lock.json
UI/src/__mocks__/contexts/AuthContext.jsx
UI/src/components/general/Navigation.test.jsx
UI/src/components/general/ProtectedRoute.test.jsx
UI/src/pages/Profile.jsx
UI/src/pages/Profile.test.jsx
UI/src/pages/Register.test.jsx
UI/src/pages/Rights.test.jsx
UI/src/pages/SignInScreen.test.jsx

[OTDELRAZRABOTKI-116] Add unit tests for Profile component

---

ContentService/build.gradle
ContentService/src/test/java/com/polytech/contentservice/service/user/UserSearchServiceImplTest.java

[OTDELRAZRABOTKI-180] Add module tests for UserSearchServiceImpl

---

UI/src/__mocks__/services/api.jsx
UI/src/hooks/useFilms.jsx
UI/src/hooks/useFilms.test.jsx

[OTDELRAZRABOTKI-181] Add unit tests for useFilms hook

---

UI/src/components/flim_components/FilmCard.jsx
UI/src/components/flim_components/FilmCard.test.jsx
UI/src/hooks/useFilms.jsx
UI/src/hooks/useFilms.test.jsx

[OTDELRAZRABOTKI-125] Add unit tests for FilmCard component

---

UI/src/pages/SignInScreen.test.jsx

[OTDELRAZRABOTKI-182] Fix race condition in unit tests for Login component

---

UI/src/components/flim_components/SearchForm.jsx
UI/src/components/flim_components/SearchForm.test.jsx
UI/src/pages/Films.jsx

[OTDELRAZRABOTKI-129] Add unit tests for SearchForm component

---

UI/src/components/flim_components/FilterPanel.test.jsx
UI/src/pages/Profile.jsx

[OTDELRAZRABOTKI-127] Add unit tests for FilterPanel component

---

UI/src/configs/testConfig.jsx
UI/src/pages/Films.test.jsx

[OTDELRAZRABOTKI-115] Add unit tests for Films component

---

UI/src/components/film_detail_components/FilmInfoSection.test.jsx

[OTDELRAZRABOTKI-124] Add unit tests for FilmInfoSection component

---

UI/src/components/film_detail_components/AddEpisodeForm.test.jsx
UI/src/components/film_detail_components/FilmEpisodesPanel.jsx
UI/src/components/film_detail_components/FilmEpisodesPanel.test.jsx

[OTDELRAZRABOTKI-123] Add unit tests for FilmEpisodesPanel component

---

IntegrationTests/.gitignore
IntegrationTests/Mocks/ChunkerServiceMock/chunker_service_mock.py
IntegrationTests/Mocks/ContentServiceMock/content_service_mock.py
IntegrationTests/Tests/conftest.py
IntegrationTests/Tests/docker-compose.integration.yml
IntegrationTests/Tests/pytest.ini
IntegrationTests/Tests/test_1/test_create_content.py

[OTDELRAZRABOTKI-173] Prepare the environment for integration tests

---

ContentService/src/main/java/com/polytech/contentservice/service/content/ContentServiceImpl.java
IntegrationTests/Tests/docker-compose.integration.yml
IntegrationTests/Tests/test_content/test_content_end_points.py

[OTDELRAZRABOTKI-185] Add integration tests for content end point

---

UI/src/__mocks__/services/api.jsx
UI/src/components/film_detail_components/FilmEpisodesPanel.jsx
UI/src/components/film_detail_components/FilmEpisodesPanel.test.jsx
UI/src/components/film_detail_components/FilmInfoSection.jsx
UI/src/components/general/EditableField.jsx
UI/src/pages/FilmDetail.jsx
UI/src/pages/FilmDetail.test.jsx

[OTDELRAZRABOTKI-114] Add unit tests for FilmDetail component

---

UI/src/App.test.jsx

[OTDELRAZRABOTKI-183] Add unit tests for App component

---

UI/src/services/api.test.jsx

[OTDELRAZRABOTKI-184] Add unit tests for api.jsx

---

IntegrationTests/Tests/docker-compose.integration.yml
IntegrationTests/Tests/test_content/test_auth_user.py
IntegrationTests/Tests/test_content/test_content_end_points.py
IntegrationTests/Tests/test_content/test_episode_end_points.py

- Add negative scenario for all integration tests
Metadata: OTDELRAZRABOTKI-186

[OTDELRAZRABOTKI-186] Add integration tests for user end point

---

ChunkerService/tests/ChunkerService.Tests/FileProcessing/FileProcessors/FileProcessorFactoryTest.cs
ChunkerService/tests/ChunkerService.Tests/FileProcessing/FileProcessors/HlsFileProcessorTest.cs

[OTDELRAZRABOTKI-189] Add Unit Tests for FileProcessors

---

ChunkerService/tests/ChunkerService.Tests/FileProcessing/FileProcessingQueueTest.cs

[OTDELRAZRABOTKI-190] Add Unit Tests for FileProcessingQueue

---

ChunkerService/tests/ChunkerService.Tests/Grpc/Interceptors/ErrorHandlerInterceptorTest.cs
ChunkerService/tests/ChunkerService.Tests/Grpc/Interceptors/TestServerCallContext.cs
ChunkerService/tests/ChunkerService.Tests/Grpc/Interceptors/ValidationInterceptorTest.cs

[OTDELRAZRABOTKI-191] Add Unit Tests for Grpc.Interceptors

---

ChunkerService/tests/ChunkerService.Tests/Grpc/MediaGrpcClientTest.cs

[OTDELRAZRABOTKI-193] Add Unit Tests for MediaGrpcClient

---

ChunkerService/tests/ChunkerService.Tests/Hls/HlsCreatorTest.cs

[OTDELRAZRABOTKI-194] Add Unit Tests for HlsCreator

---

ChunkerService/tests/ChunkerService.Tests/Repositories/ChunkerRepositoryTest.cs

[OTDELRAZRABOTKI-195] Add Unit Tests for ChunkerRepository

---

ChunkerService/tests/ChunkerService.Tests/Services/ChunkerServiceTest.cs

[OTDELRAZRABOTKI-196] Add Unit Tests for ChunkerService

---

ChunkerService/tests/ChunkerService.Tests/Services/FileProcessingServiceTest.cs

[OTDELRAZRABOTKI-197] Add Unit Tests for FileProcessingService

---

ChunkerService/tests/ChunkerService.Tests/Services/FileServiceTest.cs

[OTDELRAZRABOTKI-198] Add Unit Tests for FileService

---

ChunkerService/tests/ChunkerService.Tests/Utils/ProcessRunners/FfmpegProcessRunnerTest.cs

[OTDELRAZRABOTKI-199] Add Unit Tests for FfmpegProcessRunner

---

.gitignore
AuthService/.gitignore
AuthService/coverlet.runsettings.xml
AuthService/run-tests.bat
AuthService/tests/AuthService.Tests/Utils/Configuration/ExtentionsTest.cs
AuthService/tests/AuthService.Tests/Utils/Exceptions/AuthServiceExceptionTest.cs
AuthService/tests/AuthService.Tests/Utils/Exceptions/InvalidCredentialsExceptionTest.cs
AuthService/tests/AuthService.Tests/Utils/Exceptions/TokenValidationExceptionTest.cs
ChunkerService/.gitignore
ChunkerService/coverlet.runsettings.xml
ChunkerService/run-tests.bat
ChunkerService/src/ChunkerService/Utils/Configuration/AwsOptions.cs
ChunkerService/src/ChunkerService/Utils/Configuration/Extentions.cs
ChunkerService/tests/ChunkerService.Tests/Grpc/MediaGrpcClientTest.cs
ChunkerService/tests/ChunkerService.Tests/Utils/Configuration/AwsOptionsTest.cs
ChunkerService/tests/ChunkerService.Tests/Utils/Configuration/ExtensionsTest.cs
ChunkerService/tests/ChunkerService.Tests/Utils/Configuration/MiniValidationValidateOptionsTest.cs
MediaService/.gitignore
MediaService/coverlet.runsettings.xml
MediaService/run-tests.bat
MediaService/src/MediaService/MediaService.csproj
MediaService/src/MediaService/Utils/Configuration/AwsOptions.cs
MediaService/src/MediaService/Utils/Configuration/Extentions.cs
MediaService/tests/MediaService.Tests/Utils/Configuration/AwsOptionsTest.cs

[OTDELRAZRABOTKI-200] Add script to run tests

---

ContentService/src/main/java/com/polytech/contentservice/conroller/UserController.java
ContentService/src/main/java/com/polytech/contentservice/mapper/UserMapper.java
ContentService/src/test/java/com/polytech/contentservice/mapper/UserMapperTest.java

[OTDELRAZRABOTKI-186] Add module tests for UserMapper

---

MediaService/src/MediaService/Repositories/BucketRepository.cs
MediaService/tests/MediaService.Tests/Repositories/BucketRepositoryTest.cs

[OTDELRAZRABOTKI-201] Add IT for media and chunker services
